scale 400x300
skinparam BackgroundColor transparent
skinparam MinClassWidth 180
skinparam classAttributeIconSize 0
skinparam shadowing false
skinparam linetype ortho
skinparam nodesep 80
skinparam ranksep 80
hide circle

<style>
    note {
        BackgroundColor 222
        ArrowColor EDCA00
        ArrowStyle bold
        LineColor AAAAAA
    }

    classDiagram {
        BackgroundColor efefef30
        LineThickness 2
        LineColor 00000030
    }

    arrow {
        LineColor LightPink
        LineStyle bold
    }

    legend {
        LineThickness 0
        FontSize 10
        margin 20 0 10 0
    }
</style>
